services:
  - type: worker
    name: upscale-signal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        value: "426470592"
